name: "Bookmarks Boot"

on:
  push:
    branches:
      - master

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: commit
        env:
          GITHUB_REPO: LuckRain7/md2bookmarks
        run: |
          cd  dist
          git init
          git config --global user.email 763839938@qq.com
          git config --global user.name LuckRain7
          git add -A
          git commit -m "bot deploy"
          git push --force "https://${{ secrets.GITHUBTOKEN }}"@github.com/$GITHUB_REPO" master:page


# https://${GITHUB_ACTOR}:${INPUT_GITHUB_TOKEN}@github.com/${REPOSITORY}.git