name: "Bookmarks Boot"

on:
  push:
    branches:
      - master

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: commit
        run: |
          cd  dist
          git init
          git config --global user.email 763839938@qq.com
          git config --global user.name  LuckRain7
          git add .
          git commit -m "bot deploy"

      - name: push gitee
        run: |
          git push --force https://${{ secrets.GITEETOKEN }}@gitee.com/LuckRain/bookmarks.git page

      - name: push github
        run: |
          git push --force https://${{ secrets.GITHUBTOKEN }}@github.com/LuckRain7/bookmarks.git page


